// Abyssal Command lobby chrome translations. Korean is the default language;
// English is an explicit opt-in via the #lang-toggle button. This module only
// translates static UI chrome (headings, hints, buttons, labels). Runtime
// battle narration and status text generated by app.js/campaign-state.js stay
// as authored and are intentionally out of scope here.

const STORAGE_KEY = "abyssal-command-lang";
const DEFAULT_LANG = "ko";

const translations = {
  ko: {
    skipLink: "캠페인 명령으로 건너뛰기",
    "header.eyebrow": "오리지널 그림자 RTS-RPG",
    "header.subtitle": "가라앉은 문을 차지하라",
    "header.buildLabel": "오프라인 캠페인 준비 완료",
    "bgmToggle.label": "배경음악",
    "bgmToggle.aria": "웅장한 배경음악 켜고 끄기",
    "langToggle.aria": "English로 전환",
    "lobby.eyebrow": "3단계 캠페인",
    "lobby.title": "가라앉은 문을 차지하라",
    "lobby.lede": "신더 스팬, 베일 시타델, 메아리 왕좌를 가로질러 그림자 군단을 지휘하라. 모든 행동은 결정론적이며 터치와 키보드 모두로 조작할 수 있고, 기록은 이 기기에만 남는다.",
    "lobby.startButton": "새 캠페인 시작",
    "lobby.resumeButton": "로컬 캠페인 이어하기",
    "lobby.cinematicButton": "선택형 캠페인 시네마틱 재생",
    "lobby.description": "새 캠페인을 시작하면, 확인 후 현재 로컬 진행 상황이 대체됩니다.",
    "map.heading": "캠페인 지도 & 이동 경로",
    "map.hint": "파편화된 심연 도시를 가로지르는 황혼의 감시자의 여정.",
    "map.stage1Badge": "1단계",
    "map.stage2Badge": "2단계",
    "map.stage3Badge": "3단계",
    "map.node1Title": "신더 스팬",
    "map.node1Desc": "재의 메아리를 찾아 처치하고, 영혼을 추출하고, 세이블 릴레이를 점거하라.",
    "map.node2Title": "베일 시타델",
    "map.node2Desc": "빙의가 활성화된다. 두 거점을 동시에 장악해 보스의 방어막을 부숴라.",
    "map.node3Title": "메아리 왕좌",
    "map.node3Desc": "군주의 영역이 해금된다. 게이트 소버린을 처치해 캠페인을 마무리하라.",
    "storyboard.heading": "황혼의 감시자 실록",
    "storyboard.hint": "그림자 추출과 전술 빙의 루프의 시각 기록.",
    "storyboard.card00Title": "00. 문이 열리다",
    "storyboard.card00Desc": "달의 균열이 해안 지구로 메아리 심연의 물질을 방출한다.",
    "storyboard.card01Title": "01. 영혼 추출",
    "storyboard.card01Desc": "재의 메아리를 처치하고 \"일어나라\"를 외쳐 그림자 유닛을 실체화하라.",
    "storyboard.card03Title": "03. 전술 빙의",
    "storyboard.card03Desc": "그림자 유닛을 직접 조종해 정밀한 전투 기동을 수행하라.",
    "storyboard.card04Title": "04. 영역 전환",
    "storyboard.card04Desc": "군주의 영역을 발동해 군단에게 일시적 무적을 부여하라.",
    "storyboard.card07Title": "07. 귀환과 계승",
    "storyboard.card07Desc": "심연의 성소로 귀환해 영구 그림자 수용력을 강화하라.",
    "features.heading": "예정된 사령부 체계",
    "features.hint": "심연 저편에서 구상 중인 확장 시스템의 미리보기.",
    "features.shop.tag": "예정",
    "features.shop.title": "상점 · 교환소",
    "features.shop.body": "거둔 영혼과 파편을 바쳐 군단의 외형과 힘을 해금할 교환소가 열립니다.",
    "features.communication.tag": "구상 중",
    "features.communication.title": "교신 · 군단 결속",
    "features.communication.body": "언젠가 황혼의 감시자들이 유령 메아리를 남기고 군단의 결속을 맺게 됩니다.",
    "features.interface.tag": "예정",
    "features.interface.title": "사령부 형상 개조",
    "features.interface.body": "명령 패널 배치와 심연 테마, 접근성 설정으로 사령부를 당신의 방식으로 빚으십시오.",
    "screen.retryButton": "스테이지 재시도",
    "status.heading": "지휘 상태",
    "status.souls": "영혼",
    "status.legion": "군단 슬롯",
    "status.nodes": "점거 거점",
    "status.integrity": "군주 내구도",
    "command.heading": "의미 기반 명령",
    "command.hint": "버튼을 사용하거나, 다른 컨트롤에 포커스가 없을 때 표시된 키를 누르세요.",
    "command.hunt.name": "사냥",
    "command.hunt.desc": "균열 흔적 두 곳을 탐색",
    "command.extract.name": "추출",
    "command.extract.desc": "그림자 은닉처를 확보",
    "command.materialize.name": "실체화",
    "command.materialize.desc": "그림자 군단을 소환",
    "command.capture.name": "점거",
    "command.capture.desc": "기술 거점을 고정",
    "command.possess.name": "빙의",
    "command.possess.desc": "2단계에서 해금",
    "command.domain.name": "군주의 영역",
    "command.domain.desc": "3단계에서 1회 사용",
    "command.assault.name": "총공격",
    "command.assault.desc": "스테이지 보스를 무너뜨림",
    "reward.eyebrow": "특별 보상",
    "reward.heading": "영구 보너스 하나를 선택하라",
    "reward.summary": "선택하지 않은 보상은 균열 속으로 사라집니다.",
    "completion.eyebrow": "캠페인 완료",
    "completion.heading": "가라앉은 문이 침묵하다",
    "completion.restartButton": "새로운 캠페인 시작",
    "save.heading": "로컬 캠페인 저장",
    "save.exportButton": "저장 내보내기",
    "save.importButton": "저장 불러오기",
    "save.hint": "캠페인 상태는 버전이 관리되는 IndexedDB 봉투에 로컬로 저장됩니다. 브라우저 데이터를 지우기 전에 파일로 내보내세요.",
    noscript: "Abyssal Command 캠페인을 지휘하려면 JavaScript가 필요합니다."
  },
  en: {
    skipLink: "Skip to campaign commands",
    "header.eyebrow": "Original shadow RTS-RPG",
    "header.subtitle": "Claim the drowned gate",
    "header.buildLabel": "Offline campaign ready",
    "bgmToggle.label": "Theme",
    "bgmToggle.aria": "Toggle the epic theme music",
    "langToggle.aria": "Switch to Korean",
    "lobby.eyebrow": "Three-stage campaign",
    "lobby.title": "Claim the drowned gate",
    "lobby.lede": "Command a shadow legion across Cinder Span, Veil Citadel, and Echo Throne. Every action is deterministic, works by touch or keyboard, and remains on this device.",
    "lobby.startButton": "Start new campaign",
    "lobby.resumeButton": "Resume local campaign",
    "lobby.cinematicButton": "Play optional campaign cinematic",
    "lobby.description": "New campaign replaces the current local run only after you confirm.",
    "map.heading": "Campaign Map & Movement Path",
    "map.hint": "The path of the Dusk Warden across the fractured abyssal city.",
    "map.stage1Badge": "Stage 1",
    "map.stage2Badge": "Stage 2",
    "map.stage3Badge": "Stage 3",
    "map.node1Title": "Cinder Span",
    "map.node1Desc": "Locate and defeat Ash Echoes, extract souls, and capture the Sable Relay.",
    "map.node2Title": "Veil Citadel",
    "map.node2Desc": "Possession becomes active. Hold two nodes concurrently to break the boss shield.",
    "map.node3Title": "Echo Throne",
    "map.node3Desc": "Lord's Domain is unlocked. Defeat the Gate Sovereign to close the campaign.",
    "storyboard.heading": "Dusk Warden's Codex",
    "storyboard.hint": "Visual records of the shadow extraction and tactical possession loop.",
    "storyboard.card00Title": "00. Opening Gate",
    "storyboard.card00Desc": "A lunar fracture releases Echo Deep matter into coastal districts.",
    "storyboard.card01Title": "01. Soul Extraction",
    "storyboard.card01Desc": "Defeat Ash Echoes and invoke \"Arise\" to materialize shadow units.",
    "storyboard.card03Title": "03. Tactical Possession",
    "storyboard.card03Desc": "Directly control shadow units to execute precise combat maneuvers.",
    "storyboard.card04Title": "04. Domain Shift",
    "storyboard.card04Desc": "Unleash the Lord's Domain to grant temporary invulnerability to your legion.",
    "storyboard.card07Title": "07. Return & Persist",
    "storyboard.card07Desc": "Return to the Abyssal Shrine to upgrade your permanent shadow capacity.",
    "features.heading": "Planned Command Systems",
    "features.hint": "A preview of expansion systems taking shape beyond the rift.",
    "features.shop.tag": "Planned",
    "features.shop.title": "Soul Exchange",
    "features.shop.body": "Offer souls and fragments to unlock legion cosmetics and upgrades.",
    "features.communication.tag": "Concept",
    "features.communication.title": "Ghost-Echo Bonds",
    "features.communication.body": "A future road may let Dusk Wardens leave ghost echoes and forge legion bonds.",
    "features.interface.tag": "Planned",
    "features.interface.title": "Command Sanctum",
    "features.interface.body": "Reshape panel layouts, abyssal themes, and accessibility options for your command.",
    "screen.retryButton": "Retry stage",
    "status.heading": "Command status",
    "status.souls": "Souls",
    "status.legion": "Legion slots",
    "status.nodes": "Nodes held",
    "status.integrity": "Lord integrity",
    "command.heading": "Semantic commands",
    "command.hint": "Use buttons, or press the shown key while a control is not focused.",
    "command.hunt.name": "Hunt",
    "command.hunt.desc": "Map two rift spoor",
    "command.extract.name": "Extract",
    "command.extract.desc": "Claim the shade cache",
    "command.materialize.name": "Materialize",
    "command.materialize.desc": "Raise shadow legion",
    "command.capture.name": "Capture",
    "command.capture.desc": "Anchor a tech node",
    "command.possess.name": "Possess",
    "command.possess.desc": "Unlocks in Stage 2",
    "command.domain.name": "Lord's Domain",
    "command.domain.desc": "One use in Stage 3",
    "command.assault.name": "Assault",
    "command.assault.desc": "Break the stage boss",
    "reward.eyebrow": "Exclusive reward",
    "reward.heading": "Choose one lasting boon",
    "reward.summary": "The other reward will be lost to the rift.",
    "completion.eyebrow": "Campaign complete",
    "completion.heading": "The drowned gate is silent",
    "completion.restartButton": "Begin another campaign",
    "save.heading": "Local campaign save",
    "save.exportButton": "Export save",
    "save.importButton": "Import save",
    "save.hint": "Campaign state is stored locally in a versioned IndexedDB envelope. Export a file before clearing browser data.",
    noscript: "JavaScript is required to command the Abyssal Command campaign."
  }
};

function currentLang() {
  try {
    const stored = window.localStorage.getItem(STORAGE_KEY);
    if (stored === "ko" || stored === "en") return stored;
  } catch {
    // localStorage unavailable (private mode, etc.) — fall through to default.
  }
  return DEFAULT_LANG;
}

function applyLanguage(lang) {
  const dict = translations[lang] || translations[DEFAULT_LANG];
  document.documentElement.lang = lang;
  document.querySelectorAll("[data-i18n]").forEach((element) => {
    const key = element.dataset.i18n;
    if (Object.prototype.hasOwnProperty.call(dict, key)) {
      element.textContent = dict[key];
    }
  });
  document.querySelectorAll("[data-i18n-aria]").forEach((element) => {
    const key = element.dataset.i18nAria;
    if (Object.prototype.hasOwnProperty.call(dict, key)) {
      element.setAttribute("aria-label", dict[key]);
    }
  });
  const toggle = document.querySelector("#lang-toggle");
  if (toggle) {
    toggle.textContent = lang === "ko" ? "EN" : "한국어";
    toggle.setAttribute("aria-pressed", lang === "en" ? "true" : "false");
  }
}

function setLanguage(lang) {
  try {
    window.localStorage.setItem(STORAGE_KEY, lang);
  } catch {
    // Ignore persistence failures; the session still gets the requested language.
  }
  applyLanguage(lang);
}

function initI18n() {
  applyLanguage(currentLang());
  const toggle = document.querySelector("#lang-toggle");
  toggle?.addEventListener("click", () => {
    setLanguage(currentLang() === "ko" ? "en" : "ko");
  });
}

initI18n();

export { applyLanguage, setLanguage, currentLang, translations };
